# Generated by Django 5.2.14 on 2026-05-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('lesson_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID занятия')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(verbose_name='Дата обновления')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
                'db_table': 'attendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('discipline_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID дисциплины')),
                ('name', models.CharField(max_length=255, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'db_table': 'discipline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID факультета')),
                ('name', models.CharField(max_length=255, verbose_name='Название факультета')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
                'db_table': 'faculty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID результата')),
                ('result_value', models.CharField(max_length=50, verbose_name='Значение результата')),
            ],
            options={
                'verbose_name': 'Тип результата',
                'verbose_name_plural': 'Типы результатов',
                'db_table': 'result_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID специальности')),
                ('name', models.CharField(max_length=255, verbose_name='Название специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'db_table': 'speciality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID студента')),
                ('birthday', models.TextField(blank=True, null=True, verbose_name='Дата рождения')),
                ('is_academic', models.BooleanField(default=False, verbose_name='В академическом отпуске')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID группы')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа студентов',
                'verbose_name_plural': 'Группы студентов',
                'db_table': 'student_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Результат студента',
                'verbose_name_plural': 'Результаты студентов',
                'db_table': 'student_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='administrator_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='administrator_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
    ]
