# Generated by Django 5.0.14 on 2026-05-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'managed': False, 'verbose_name': 'Посещаемость', 'verbose_name_plural': 'Посещаемость'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'managed': False, 'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'managed': False, 'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='resulttype',
            options={'managed': False, 'verbose_name': 'Тип результата', 'verbose_name_plural': 'Типы результатов'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'managed': False, 'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False, 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'managed': False, 'verbose_name': 'Группа студентов', 'verbose_name_plural': 'Группы студентов'},
        ),
        migrations.AlterModelOptions(
            name='studentresult',
            options={'managed': False, 'verbose_name': 'Результат студента', 'verbose_name_plural': 'Результаты студентов'},
        ),
    ]
